import localFont from "next/font/local";
import "./globals.css";


const estedad = localFont({
  src: "./fonts/Estedad.woff2",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`antialiased bg-background ${estedad.class}`}>

        {children}
      </body>
    </html>
  );
}
